# Generated by Django 5.0.7 on 2024-08-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=200)),
                ('completado', models.BooleanField(default=False)),
            ],
        ),
    ]
